routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('alternatif', 'AltController');

Route::get('/', function () {
    return view('home');
});
Route::get('/kriteria', function(){
    $kriteria=DB::table('kriteria')->get();

    return view('kriteria',['kriteria'=>$kriteria]);
});

Route::get('/alternatif', function(){
    $alternatif=DB::table('alternatif')->get();
    $kriteria=DB::table('kriteria')->get();

    return view('alternatif',compact('kriteria','alternatif'));
});

// Route::get('/editAlternatif', function(){
//     $alternatif=DB::table('kriteria')->get();
//
//     return view('alternatif', compact('alternatif'));
// });

Route::get('/addalternatif', 'alternatifController@add');
Route::get('/editAlternatif/{$id_alternatif}', 'alternatifController@edit')-> name('editAlternatif');
Route::post('/deletealternatif/{$id_alternatif}', 'alternatifController@destroy')->name('destroy');
Route::post('/addalter', 'alternatifController@addAlternatif');
Route::get('/analisa','analisaController@analisis');
Route::get('/perhitungan','hitungController@hitung');

resources/views/addalternatif.blade.php
@extends('layouts.master')

@section('navbar')

@section('content')
<div class="panel panel-default">
    <div class="panel-body">
        @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        <form action="/addalter" method="post" enctype="multipart/form-data">
            @csrf
            {{ method_field('post') }}
          <div class="form-group {{ !$errors->has('title') ?: 'has-error' }}">
                <label>Nama Alternatif</label>
                <input type="text" name="namaAlternatif" class="form-control" placeholder="Nama Alternatif">
            </div>
            <div class="form-group {{ !$errors->has('title') ?: 'has-error' }}">
                <label>Bahan</label>
                <input type="text" name="bahan" class="form-control" placeholder="Bahan. ex : ...">
            </div>
            <div class="form-group {{ !$errors->has('title') ?: 'has-error' }}">
                <label>Jenis</label>
                <input type="text" name="jenis" class="form-control" placeholder="Jenis. ex : ...">
            </div>
            <div class="form-group {{ !$errors->has('title') ?: 'has-error' }}">
                <label>Bentuk</label>
                <input type="text" name="bentuk" class="form-control" placeholder="Bentuk. ex : ...">
            </div>
            <div class="form-group {{ !$errors->has('title') ?: 'has-error' }}">
                <label>Berat</label>
                <input type="text" name="berat" class="form-control" placeholder="Berat. ex : ...">
            </div>
            <div class="form-group {{ !$errors->has('title') ?: 'has-error' }}">
                <label>Harga</label>
                <input type="text" name="harga" class="form-control" placeholder="Harga. ex : ...">
            </div>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Tambah Alternatif Baru</button>
                <a href="/alternatif" class="btn btn-warning">Kembali</a>
            </div>
        </form>
    </div>
</div>
</div>
@stop

resources/views/alternatif.blade.php
@extends('layouts.master')

@section('navbar')

@section('content')

		 <!-- Main component for a primary marketing message or call to action -->
         <div class="panel panel-primary">
		  <!-- Default panel contents -->
		  <div class="panel-heading">Data Alternatif</div>
						<?php
							//include 'config.php';
							// 				$kriteria = $mysqli->query("select * from kriteria");
							// 				if(!$kriteria){
							// 					echo $mysqli->connect_errno." - ".$mysqli->connect_error;
							// 					exit();
							// 				}
							// 				$i=0;
							// 				while ($row = $kriteria->fetch_assoc()) {
							// 					@$k[$i] = $row["kriteria"];
							// 					$i++;
							// 				}
							// $alternatif = $mysqli->query("select * from alternatif");
							// if(!$alternatif){
							// 	echo $mysqli->connect_errno." - ".$mysqli->connect_error;
							// 	exit();
							// }
							// $i=0;
						?>
		  <div class="panel-body table-responsive">
			<a class='btn btn-primary' href='addalternatif'> Tambah Data Alternatif</a><br /><br />
			<table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th>No.</th>
					<th>Alternatif</th>
                    @foreach($kriteria as $key=>$d)
                    <th>{{$d->kriteria}}</th>
                    @endforeach

					<th>Pilihan</th>
				</tr>

                @foreach($alternatif as $key=>$data)
                    <tr>
                    <th>{{$key+1}}</th>
                    <th>{{$data->alternatif}}</th>
                    <th>{{$data->k1}}</th>
                    <th>{{$data->k2}}</th>
                    <th>{{$data->k3}}</th>
                    <th>{{$data->k4}}</th>
                    <th>{{$data->k5}}</th>
					<th>
                    <a class="btn btn-info" href="{{route('alternatif.edit',$data->id_alternatif) }}">Edit</a>
                    <form action="{{ route('alternatif.destroy', $data->id_alternatif)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                    </th>
                    </tr>
                @endforeach
			</thead>

			<tfoot>
				<tr>
                    <th>No.</th>
					<th>Alternatif</th>
                    @foreach($kriteria as $key=>$d)
                    <th>{{$d->kriteria}}</th>
                    @endforeach
					<th>Pilihan</th>
				</tr>
			</tfoot>

			<tbody>
										<?php

										?>
			</tbody>
			</table>
		  </div>

@stop

resources/views/analisa.blade.php
@extends('layouts.master')

@section('navbar')

@section('content')

<!-- Main component for a primary marketing message or call to action -->
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Analisa</div>
  <div class="panel-body">
    <div>
      <canvas id="canvas"></canvas>
    </div>
    <br />
    <center>
    <h2>Hasil Akhir</h2>
      <table class="table table-striped table-bordered table-hover">
            <th>
              Nama
            </th>


            <th> V</th>
            @for($i=0;$i<$altcount;$i++)
          <tr>
            <td>{{ $alt_name[$i]  }}</td>
            <td>{{ $vs[$i] }}</td>

          </tr>
          @endfor
      </table>

      </table>
      <div class="alert alert-dismissible alert-info">

        @foreach($sorted as $key => $value)

          @if($key==0) <b>Dari tabel tersebut dapat disimpulkan bahwa <i>{{$value->alternatif}}</i> mempunyai hasil paling tinggi, yaitu {{$value->hasil}}</b>

          @else <p>diikuti <i>{{$value->alternatif}}</i> dengan hasil {{$value->hasil}}</p>
          @endif
        @endforeach
      </div>
    </center>
  </div>
</div>


@stop
<script>
var randomScalingFactor = function(){ return Math.round(Math.random()*100)};

var barChartData = {
  labels : [
    <?php
    for($i=0;$i<$altcount;$i++){
      echo '"'.$alt_name[$i].'",';
    }
    ?>
  ],
  datasets : [
    {
      fillColor : "rgba(0,0,255,0.75)",
      strokeColor : "rgba(220,220,220,0.8)",
      highlightFill: "rgba(0,128,255,0.75)",
      highlightStroke: "rgba(220,220,220,1)",
      data : [
        <?php
        for($i=0;$i<$altcount;$i++){
          echo $vs[$i].',';
        }
        ?>
      ]
    },
    /*{
    fillColor : "rgba(151,187,205,0.5)",
    strokeColor : "rgba(151,187,205,0.8)",
    highlightFill : "rgba(151,187,205,0.75)",
    highlightStroke : "rgba(151,187,205,1)",
    data : [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]
  }*/
]

}
window.onload = function(){
  var ctx = document.getElementById("canvas").getContext("2d");
  window.myBar = new Chart(ctx).Bar(barChartData, {
    responsive : true
  });
}

</script>

resources/views/editAlternatif.blade.php
@extends('layouts.master')

@section('navbar')

@section('content')
<div class="panel panel-default">
    <div class="panel-body">
        @if(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        @foreach ($data as $key)
        <form action="/addalter" method="post" enctype="multipart/form-data">
            @csrf
            {{ method_field('post') }}

            <div class="form-group {{ !$errors->has('title') ?: 'has-error' }}">
                <label>Bahan</label>
                <input type="text" name="bahan" class="form-control" value='{{$key->alternatif}}'>
            </div>
            <div class="form-group {{ !$errors->has('title') ?: 'has-error' }}">
                <label>Jenis</label>
                <input type="text" name="jenis" class="form-control" value='{{$key->k2}}'>
            </div>
            <div class="form-group {{ !$errors->has('title') ?: 'has-error' }}">
                <label>Bentuk</label>
                <input type="text" name="bentuk" class="form-control" value='{{$key->k3}}'>
            </div>
            <div class="form-group {{ !$errors->has('title') ?: 'has-error' }}">
                <label>Berat</label>
                <input type="text" name="berat" class="form-control" value='{{$key->k4}}'>
            </div>
            <div class="form-group {{ !$errors->has('title') ?: 'has-error' }}">
                <label>Harga</label>
                <input type="text" name="harga" class="form-control" value='{{$key->k5}}'>
            </div>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Tambah Alternatif Baru</button>
                <a href="/alternatif" class="btn btn-warning">Kembali</a>
            </div>
        </form>
        @endforeach


        <!-- @foreach ($data as $key)
          <p>{{$key->alternatif}}</p>
        @endforeach -->
    </div>
</div>
</div>
@stop

resources/views/kriteria.blade.php
@extends('layouts.master')

@section('navbar')

@section('content')

<div id="page-wrapper">
      <div class="row">
      <div class="col-lg-12">
	  <div class="panel panel-primary">
		  <!-- Default panel contents -->
		  <div class="panel-heading">Data Kriteria</div>
		    <?php
							// $kriteria = $mysqli->query("select * from kriteria");
							// if(!$kriteria){
							// 	echo $mysqli->connect_errno." - ".$mysqli->connect_error;
							// 	exit();
							// }
							// $i=0;
		    ?>
		  <div class="panel-body table-responsive">
			<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th>No.</th>
					<th>Kriteria</th>					
					<th>Kepentingan</th>
					<th>Cost / Benefit</th>
					<th>Opsi</th>
				</tr>
        @foreach($kriteria as $key=>$data)
				<tr>
          <th>{{$data->id_kriteria}}</th>
					
					<th>{{$data->kriteria}}</th>
					<th>{{$data->kepentingan}}</th>
					<th>{{$data->cost_benefit}}</th>
					<th><button type="button" class="btn btn-info">Edit</button></th>
				</tr>
        @endforeach
			</thead>
		 
			<tfoot>
				<tr>
					<th>No.</th>
					<th>Kriteria</th>
					<th>Kepentingan</th>
					<th>Cost / Benefit</th>
					<th>Opsi</th>
				</tr>
			</tfoot>
		 
@stop

resources/views/perhitungan.blade.php
@extends('layouts.master')

@section('navbar')

@section('content')
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Perhitungan</div>
  <div class="panel-body">
    <center>
      <b>Matrix Alternatif - Kriteria</b>
      <table class="table table-striped table-bordered table-hover">
        <thead><tr><th>Alternatif / Kriteria</th><th>K1</th><th>K2</th><th>K3</th><th>K4</th><th>K5</th></tr></thead>
        @foreach($alternatif as $key => $v)
        <tr>
          <td>{{$v->alternatif}}</td>
          <td>{{$v->k1}}</td>
          <td>{{$v->k2}}</td>
          <td>{{$v->k3}}</td>
          <td>{{$v->k4}}</td>
          <td>{{$v->k5}}</td>

        </tr>
        @endforeach
      </table><hr>

      <b>Perhitungan Bobot Kepentingan</b>
      <table class="table table-striped table-bordered table-hover">
        <thead><tr><th></th><th>K1</th><th>K2</th><th>K3</th><th>K4</th><th>K5</th><th>Jumlah</th></tr></thead>
        <tr>
          <td><b>Kepentingan</b></td>
          @foreach($kriteria as $key => $v)
          <td>{{$v->kepentingan}}</td>
          @endforeach
          <td>{{$tkep}}</td>
        </tr>
          <tr>
            <td>
              <b>Bobot Kepentingan</b>
            </td>
            @foreach($bkep as $key => $v)
            <td>{{$v}}</td>
            @endforeach
            <td>{{$jumlah}}</td>
          </tr>
          </table><hr>

          <b>Perhitungan Pangkat</b>
          <table class="table table-striped table-bordered table-hover">
            <thead><tr><th></th><th>K1</th><th>K2</th><th>K3</th><th>K4</th><th>K5</th></tr></thead>

            <tr>
              <td><b>Cost/Benefit</b></td>
              @foreach($kriteria as $key => $v)
              <td>{{$v->cost_benefit}}</td>
              @endforeach
            </tr>
              <tr>
                <td><b>Pangkat</b></td>
                @foreach($pangkat as $key => $v)
                <td>{{$v}}</td>
                @endforeach
              </tr>
          </table><hr>

              <b>Perhitungan Nilai S</b>
              <table class="table table-striped table-bordered table-hover">
                <thead>
                  <tr>
                    <th>Alternatif</th>
                    <th>S</th>
                  </tr>
                </thead>
                @foreach($ss as $key => $v)
                <tr>
                  <td>A{{$key}}</td>
                  <td>{{ $v }}</td>
                </tr>
                @endforeach
                <!-- <tr>
                  <td>tada</td>
                  <td>tada</td>
                </tr>
                <tr>
                  <td>tada</td>
                  <td>tada</td>
                </tr> -->
              </table><hr>

              <b>Hasil Akhir</b>
              <table class="table table-striped table-bordered table-hover">
                <th>
                  Nama
                </th>
                <th> V</th>
                @for($i=0;$i<$altcount;$i++)
              <tr>
                <td>{{ $alt_name[$i]  }}</td>
                <td>{{ $vs[$i] }}</td>
              </tr>
              @endfor
              </table><hr>
            <div class="alert alert-dismissible alert-info">

              @foreach($sorted as $key => $value)

                @if($key==0) <b>Dari tabel tersebut dapat disimpulkan bahwa <i>{{$value->alternatif}}</i> mempunyai hasil paling tinggi, yaitu {{$value->hasil}}</b>

                @else <p>diikuti <i>{{$value->alternatif}}</i> dengan hasil {{$value->hasil}}</p>
                @endif
              @endforeach
            </div>
          </center>
          </div>
        </div>
        @stop